### ISSUE TITLE
ssft_utils gives an TypeError wiht numpy 1.13.0

### ISSUE THREAD

**Issue by cvelascof** [dnerini/ssft-generator#1]
Hi Daniele

For some reason if you are using numpy 1.13.0 and py35_0 your main.py gets this error message.

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-3-7b301479f060> in <module>()
>       4 winsize1 = rainField_dBZ.shape[0]
>       5 overlap1 = 0
> ----> 6 corrNoiseGlobal = ssft_generator(rainField_dBZ, winsize=winsize1, overlap=overlap1)
>       7 
> 
> ~/code/ssft-generator-v1.0.0/dnerini-ssft-generator-52e9bf0/ssft_utils.py in ssft_generator(rainField, winsize, overlap)
>      77                 mask = np.zeros(rainField.shape)
>      78 
> ---> 79                 mask[idxi[0]:idxi[1],idxj[0]:idxj[1]] = wind
> 
> TypeError: only integer scalar arrays can be converted to a scalar index

The solution is to replace line 79 in ssft_utils.py 
from:
                mask[idxi[0]:idxi[1],idxj[0]:idxj[1]] = wind
to:
                mask[idxi.item(0):idxi.item(1),idxj.item(0):idxj.item(1)] = wind

Cheers

Carlos

**Comment by dnerini** [comment]
Hi Carlos
the change you suggest is now merged with the main branch. Thanks a lot for it!
Kind regards,
Daniele
